default:
  http_metas:
    content-type: text/html

  metas:
    title:        "Singapore Labeling (thermopatch) :: Micronclean Singapore"
    robots:       index, follow
    description:  Micronclean Singapore
    keywords:     micronclean, singapore
    language:     en

  stylesheets: [style]

  javascripts: [script]


  has_layout:     on
  layout:         layout
